version: '3.1'
services:
  db:
    container_name: marakas-postgres-db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marakas
  adminer:
    container_name: marakas-adminer
    image: adminer:4.7.7
    depends_on:
      - db
    ports:
      - 8080:8080